<script src="<?= base_url(); ?>assets/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="<?= base_url(); ?>assets/font-awesome/js/all.min.js"></script>
<script src="<?= base_url(); ?>assets/bootstrap-table/dist/bootstrap-table.min.js"></script>
<script src="<?= base_url(); ?>assets/dist/js/glightbox.min.js"></script>
<script src="<?= base_url(); ?>assets/bootstrap-table/dist/tableExport.min.js"></script>
<script src="<?= base_url(); ?>assets/bootstrap-table/dist/bootstrap-table-locale-all.min.js"></script>
<script src="<?= base_url(); ?>assets/bootstrap-table/dist/extensions/export/bootstrap-table-export.min.js"></script>
<script src="<?= base_url(); ?>assets/bootstrap-table/dist/extensions/cookie/bootstrap-table-cookie.min.js"></script>
<script src="<?= base_url(); ?>assets/bootstrap-table/dist/locale/bootstrap-table-en-US.min.js"></script>
<script src="<?= base_url(); ?>assets/jquery/dist/jquery-ui.js"></script>
<script src="<?= base_url(); ?>assets/richtext/jquery.richtext.min.js"></script>
<script src="<?= base_url(); ?>assets/js/scripts-admin.js"></script>
